version: '3'
services:
  db:
    container_name: guacamole-db
    networks:
      - lab
    image: postgres:13
    volumes:
      - $PWD/guacamole/conf/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - $PWD/guacamole/data:/var/lib/postgresql/data
    env_file: $PWD/guacamole/.env
  daemon:
    container_name: guacamole-daemon
    networks:
      - lab
    image: guacamole/guacd:1.3.0
    depends_on:
      - db 
  web:
    container_name: guacamole-web
    networks:
      - lab
    image: guacamole/guacamole:1.3.0
    ports:
      - "8080:8080"
    env_file: $PWD/guacamole/.env
    depends_on:
      - daemon
  
  proxy:
    container_name: guacamole-proxy
    networks:
      - lab
    image: nginx:1
    ports:
      - "80:80"
    restart: always
    volumes:
      - $PWD/guacamole/conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
networks:
  lab:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24